options:
  job_size:
    type: string
    default: 10000000
    description: number of 100byte rows to generate
  job_maps:
    type: string
    default: 100
    description: number of maps for gen
  job_reduces:
    type: string
    default: 100
    description: number of reduces for sort
  job_data_dir:
    type: string
    default: in_dir
    description: job data directory
  job_output_dir:
    type: string
    default: out_dir
    description: job output directory
