#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot


############################################################################################################
# Set debugging
############################################################################################################

set -ux
juju-log "install script"


############################################################################################################
# Add the repositories
############################################################################################################

export TERM=linux

#RELEASE_CODE=`lsb_release -a | awk '/Codename/ { print $2 }'`

# Add the Hadoop PPA
juju-log "Adding ppa"
apt-add-repository ppa:mark-mims/hadoop
#apt-add-repository ppa:canonical-sig/thirdparty
juju-log "updating cache"
apt-get update


############################################################################################################
# Calculate our IP Address
############################################################################################################

juju-log "calculating ip"
HOSTNAME=`hostname -f`
IP_ADDRESS=`hostname -f | xargs dig +short`
juju-log "Private IP: ${IP_ADDRESS}"

# only necessary on oneiric but shouldn't break anything elsewhere
#sed -i "s/\(.*${HOSTNAME}.*\)/#\1/" /etc/hosts
sed -i "s/127.0.1.1\(.*${HOSTNAME}.*\)/${IP_ADDRESS}\1/" /etc/hosts



############################################################################################################
# Preseed our Namenode, Jobtracker and HDFS Data directory
############################################################################################################

NAMENODE="${HOSTNAME}"
JOBTRACKER="${HOSTNAME}"
HDFSDATADIR="/var/lib/hadoop-0.20/dfs/data"
juju-log "Namenode: ${NAMENODE}"
juju-log "Jobtracker: ${JOBTRACKER}"
juju-log "HDFS Dir: ${HDFSDATADIR}"

echo debconf hadoop/namenode string ${NAMENODE}| /usr/bin/debconf-set-selections
echo debconf hadoop/jobtracker string ${JOBTRACKER}| /usr/bin/debconf-set-selections
echo debconf hadoop/hdfsdatadir string ${HDFSDATADIR}| /usr/bin/debconf-set-selections


############################################################################################################
# Install the packages
############################################################################################################

juju-log "installing packages"
apt-get install -y hadoop-0.20-namenode
apt-get install -y hadoop-0.20-jobtracker


# set bind-address...
#sed -i 's###' /etc/hadoop/conf/hadoop-env.sh
#echo "export HADOOP_OPTS=-Djava.net.preferIPv4Stack=true" >> /etc/hadoop/conf/hadoop-env.sh



############################################################################################################
# Open the necessary ports
############################################################################################################

if [ -x /usr/bin/open-port ];then
   open-port 50010/TCP
   open-port 50020/TCP
   open-port 50030/TCP
   open-port 50105/TCP
   open-port 54310/TCP
   open-port 54311/TCP
   open-port 50060/TCP
   open-port 50070/TCP
   open-port 50075/TCP
   open-port 50090/TCP
fi
