#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
set -x
ensemble-log "start script"
service hadoop-0.20-namenode restart
service hadoop-0.20-jobtracker restart
